services:
  - type: web
    name: ev-charge-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENCAGE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ev-users-db
          property: connectionString

databases:
  - name: ev-users-db
    plan: free
